{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PCC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"grid_power_watts\" FROM \"power_metrics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"production_power_watts\" FROM \"power_metrics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Battery Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"battery_power_watts\" FROM \"power_metrics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "SoC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"battery_soc\" FROM \"power_metrics\""
    }
   ]
  },
  {
   "title": "PCC",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"grid_power_watts\" FROM \"power_metrics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "PV Production",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"production_power_watts\" FROM \"power_metrics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Battery Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"battery_power_watts\" FROM \"power_metrics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Battery SoC",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"battery_soc\" FROM \"power_metrics\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  }
 ]
}