name: frequenz-sdk-tests
base: core24 # maybe we have to use core22 and figure out how to switch the python version
version: '0.1'
summary: Frequenz SDK test cases for HiL
description: |
  This package provides test cases for the HiL setup written in the frequenz-sdk.
platforms:
  amd64:
  arm64:
    build-on: [amd64]
    build-for: [arm64]

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  sdk-apps:
    source: .
    plugin: python

# TODO check if all apps need the network and the network-bind plugin
apps:
  test:
    # This file should run all tests sequentially
    command: bin/on_grid
    plugs:
      - network
      - network-bind
